AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  SubnetID:
    Type: String
  MYSecurityGroup:
    Type: String
Resources:
  k8sclient: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: "ami-02f3416038bdb17fb"
      KeyName:  "ohio"
      InstanceType: "t2.micro"
      NetworkInterfaces: 
      - AssociatePublicIpAddress: "true"
        DeviceIndex: "0"
        SubnetId: 
          Ref: "SubnetID"
  k8smaster: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: "ami-02f3416038bdb17fb"
      KeyName:  "ohio"
      InstanceType: "t2.large"
      NetworkInterfaces: 
      - AssociatePublicIpAddress: "true"
        DeviceIndex: "0"
        SubnetId: 
          Ref: "SubnetID"
  k8snode01: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: "ami-02f3416038bdb17fb"
      KeyName:  "ohio"
      InstanceType: "t2.medium"
      NetworkInterfaces: 
      - AssociatePublicIpAddress: "true"
        DeviceIndex: "0"
        SubnetId: 
          Ref: "SubnetID"
